from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Graph program")
        Dialog.resize(390, 300)
        Dialog.setFixedSize(390, 300)

        self.generateComboBox = QtWidgets.QComboBox(Dialog)
        self.generateComboBox.setGeometry(QtCore.QRect(210, 10, 175, 25))
        self.generateComboBox.setObjectName("generateComboBox")
        self.generateComboBox.addItem("")
        self.generateComboBox.addItem("")
        self.generateComboBox.addItem("")
        self.generateLabel = QtWidgets.QLabel(Dialog)
        self.generateLabel.setGeometry(QtCore.QRect(10, 10, 180, 25))
        self.generateLabel.setObjectName("generateLabel")

        self.attackLabel = QtWidgets.QLabel(Dialog)
        self.attackLabel.setGeometry(QtCore.QRect(10, 40, 180, 25))
        self.attackLabel.setObjectName("attackLabel")
        self.attackComboBox = QtWidgets.QComboBox(Dialog)
        self.attackComboBox.setGeometry(QtCore.QRect(210, 40, 175, 25))
        self.attackComboBox.setObjectName("attackComboBox")
        self.attackComboBox.addItem("")
        self.attackComboBox.addItem("")
        self.attackComboBox.addItem("")
        self.attackComboBox.addItem("")
        self.attackComboBox.addItem("")
        self.attackComboBox.addItem("")

        self.sizeLabel = QtWidgets.QLabel(Dialog)
        self.sizeLabel.setGeometry(QtCore.QRect(10, 70, 180, 25))
        self.sizeLabel.setObjectName("sizeLabel")
        self.sizeBox = QtWidgets.QSpinBox(Dialog)
        self.sizeBox.setGeometry(QtCore.QRect(210, 70, 175, 25))
        self.sizeBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.sizeBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sizeBox.setAutoFillBackground(False)
        self.sizeBox.setMaximum(10000)
        self.sizeBox.setProperty("value", 100)
        self.sizeBox.setObjectName("sizeBox")

        self.rewritingBox = QtWidgets.QSpinBox(Dialog)
        self.rewritingBox.setGeometry(QtCore.QRect(210, 100, 175, 25))
        self.rewritingBox.setMinimum(1)
        self.rewritingBox.setProperty("value", 5)
        self.rewritingBox.setObjectName("rewritingBox")
        self.nodesLabel = QtWidgets.QLabel(Dialog)
        self.nodesLabel.setGeometry(QtCore.QRect(10, 100, 200, 25))
        self.nodesLabel.setObjectName("nodesLabel")

        self.retryBox = QtWidgets.QSpinBox(Dialog)
        self.retryBox.setGeometry(QtCore.QRect(210, 130, 175, 25))
        self.retryBox.setMaximum(10000)
        self.retryBox.setProperty("value", 1000)
        self.retryBox.setObjectName("retryBox")
        self.retryLabel = QtWidgets.QLabel(Dialog)
        self.retryLabel.setGeometry(QtCore.QRect(10, 130, 200, 16))
        self.retryLabel.setObjectName("retryLabel")

        self.seedBox = QtWidgets.QSpinBox(Dialog)
        self.seedBox.setEnabled(False)
        self.seedBox.setGeometry(QtCore.QRect(210, 160, 175, 25))
        self.seedBox.setObjectName("seedBox")
        self.seedCheckBox = QtWidgets.QCheckBox(Dialog)
        self.seedCheckBox.setGeometry(QtCore.QRect(190, 160, 16, 25))
        self.seedCheckBox.setText("")
        self.seedCheckBox.setObjectName("seedCheckBox")
        self.seedLabel = QtWidgets.QLabel(Dialog)
        self.seedLabel.setGeometry(QtCore.QRect(10, 160, 180, 25))
        self.seedLabel.setObjectName("seedLabel")

        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setEnabled(False)
        self.progressBar.setGeometry(QtCore.QRect(10, 200, 380, 25))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")

        self.startButton = QtWidgets.QPushButton(Dialog)
        self.startButton.setGeometry(QtCore.QRect(145, 250, 100, 25))
        self.startButton.setObjectName("startButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle('Graphs')
        Dialog.setWindowIcon(QIcon('main.png'))
        self.startButton.setText(_translate("Dialog", "Start"))
        self.generateLabel.setText(_translate("Dialog", "Метод генерации графа"))
        self.attackLabel.setText(_translate("Dialog", "Метод атаки на граф"))
        self.sizeLabel.setText(_translate("Dialog", "Количество вершин у графа"))
        self.generateComboBox.setItemText(0, _translate("Dialog", "Случайный"))
        self.generateComboBox.setItemText(1, _translate("Dialog", "Барабаши-Альберт"))
        self.generateComboBox.setItemText(2, _translate("Dialog", "Ватц-Строгац"))
        self.attackComboBox.setItemText(0, _translate("Dialog", "Случайная"))
        self.attackComboBox.setItemText(1, _translate("Dialog", "Максимальная связность"))
        self.attackComboBox.setItemText(2, _translate("Dialog", "Минимальная связность"))
        self.attackComboBox.setItemText(3, _translate("Dialog", "Центральность"))
        self.attackComboBox.setItemText(4, _translate("Dialog", "Центральность с перерасчётом"))
        self.attackComboBox.setItemText(5, _translate("Dialog", "Кластеризация"))
        self.nodesLabel.setText(_translate("Dialog", "Cреднее количество узлов у вершин"))
        self.seedLabel.setText(_translate("Dialog", "Задать определенное значение?"))
        self.retryLabel.setText(_translate("Dialog", "Введите количество повторов"))
